-- Run once in Supabase SQL editor (or psql) after `teams` exists.
-- Playoff player stats + roster rows mirror `teamRosters`; season_id is 92.

create table if not exists public."playoffStats" (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  team text null,
  player_name text null,
  position text null,
  games_played smallint null,
  goals smallint null,
  assists smallint null,
  points integer null,
  "plusMinus" smallint null,
  penalty_minutes integer null,
  power_play_goals smallint null,
  number text null,
  rookie boolean null,
  veteran boolean null,
  "lastSynced" timestamp with time zone null,
  season_id integer null default 92,
  constraint playoffStats_pkey primary key (id),
  constraint playoffStats_team_fkey foreign key (team) references teams (abbreviation)
) tablespace pg_default;

create index if not exists idx_playoff_stats_team on public."playoffStats" using btree (team) tablespace pg_default;
